import { useState } from 'react';

const App = () => {
  const [persons, setPersons] = useState([{ name: 'Arto Hellas' }]);
    const [newName, setNewName] = useState('');

      const handleNameChange = (event) => {
          setNewName(event.target.value);
            };

              const addPerson = (event) => {
                  event.preventDefault();

                      // Check if name already exists (case insensitive)
                          if (persons.some(person => person.name.toLowerCase() === newName.toLowerCase())) {
                                alert(`${newName} is already added to the phonebook`);
                                      return;
                                          }

                                              setPersons([...persons, { name: newName }]);
                                                  setNewName('');
                                                    };

                                                      return (
                                                          <div style={styles.container}>
                                                                <h2 style={styles.title}>Phonebook</h2>
                                                                      <form onSubmit={addPerson} style={styles.form}>
                                                                              <div style={styles.inputGroup}>
                                                                                        <label style={styles.label}>Name:</label>
                                                                                                  <input 
                                                                                                              value={newName} 
                                                                                                                          onChange={handleNameChange} 
                                                                                                                                      style={styles.input} 
                                                                                                                                                  placeholder="Enter name"
                                                                                                                                                            />
                                                                                                                                                                    </div>
                                                                                                                                                                            <button type="submit" style={styles.button}>Add</button>
                                                                                                                                                                                  </form>

                                                                                                                                                                                        <h2 style={styles.title}>Numbers</h2>
                                                                                                                                                                                              <ul style={styles.list}>
                                                                                                                                                                                                      {persons.map(person => (
                                                                                                                                                                                                                <li key={person.name} style={styles.listItem}>
                                                                                                                                                                                                                            {person.name}
                                                                                                                                                                                                                                      </li>
                                                                                                                                                                                                                                              ))}
                                                                                                                                                                                                                                                    </ul>
                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                          );
                                                                                                                                                                                                                                                          };

                                                                                                                                                                                                                                                          // Styles for responsiveness and clarity
                                                                                                                                                                                                                                                          const styles = {
                                                                                                                                                                                                                                                            container: {
                                                                                                                                                                                                                                                                fontFamily: 'Arial, sans-serif',
                                                                                                                                                                                                                                                                    maxWidth: '400px',
                                                                                                                                                                                                                                                                        margin: '20px auto',
                                                                                                                                                                                                                                                                            padding: '20px',
                                                                                                                                                                                                                                                                                borderRadius: '10px',
                                                                                                                                                                                                                                                                                    boxShadow: '0 0 10px rgba(0, 0, 0, 0.1)',
                                                                                                                                                                                                                                                                                        backgroundColor: '#f9f9f9',
                                                                                                                                                                                                                                                                                          },
                                                                                                                                                                                                                                                                                            title: {
                                                                                                                                                                                                                                                                                                textAlign: 'center',
                                                                                                                                                                                                                                                                                                    color: '#333',
                                                                                                                                                                                                                                                                                                      },
                                                                                                                                                                                                                                                                                                        form: {
                                                                                                                                                                                                                                                                                                            display: 'flex',
                                                                                                                                                                                                                                                                                                                flexDirection: 'column',
                                                                                                                                                                                                                                                                                                                    gap: '10px',
                                                                                                                                                                                                                                                                                                                        marginBottom: '20px',
                                                                                                                                                                                                                                                                                                                          },
                                                                                                                                                                                                                                                                                                                            inputGroup: {
                                                                                                                                                                                                                                                                                                                                display: 'flex',
                                                                                                                                                                                                                                                                                                                                    alignItems: 'center',
                                                                                                                                                                                                                                                                                                                                        gap: '10px',
                                                                                                                                                                                                                                                                                                                                          },
                                                                                                                                                                                                                                                                                                                                            label: {
                                                                                                                                                                                                                                                                                                                                                fontWeight: 'bold',
                                                                                                                                                                                                                                                                                                                                                  },
                                                                                                                                                                                                                                                                                                                                                    input: {
                                                                                                                                                                                                                                                                                                                                                        flex: 1,
                                                                                                                                                                                                                                                                                                                                                            padding: '8px',
                                                                                                                                                                                                                                                                                                                                                                fontSize: '16px',
                                                                                                                                                                                                                                                                                                                                                                    borderRadius: '5px',
                                                                                                                                                                                                                                                                                                                                                                        border: '1px solid #ccc',
                                                                                                                                                                                                                                                                                                                                                                          },
                                                                                                                                                                                                                                                                                                                                                                            button: {
                                                                                                                                                                                                                                                                                                                                                                                padding: '10px',
                                                                                                                                                                                                                                                                                                                                                                                    fontSize: '16px',
                                                                                                                                                                                                                                                                                                                                                                                        color: 'white',
                                                                                                                                                                                                                                                                                                                                                                                            backgroundColor: '#007bff',
                                                                                                                                                                                                                                                                                                                                                                                                border: 'none',
                                                                                                                                                                                                                                                                                                                                                                                                    borderRadius: '5px',
                                                                                                                                                                                                                                                                                                                                                                                                        cursor: 'pointer',
                                                                                                                                                                                                                                                                                                                                                                                                          },
                                                                                                                                                                                                                                                                                                                                                                                                            list: {
                                                                                                                                                                                                                                                                                                                                                                                                                listStyleType: 'none',
                                                                                                                                                                                                                                                                                                                                                                                                                    padding: 0,
                                                                                                                                                                                                                                                                                                                                                                                                                      },
                                                                                                                                                                                                                                                                                                                                                                                                                        listItem: {
                                                                                                                                                                                                                                                                                                                                                                                                                            padding: '10px',
                                                                                                                                                                                                                                                                                                                                                                                                                                backgroundColor: 'white',
                                                                                                                                                                                                                                                                                                                                                                                                                                    borderRadius: '5px',
                                                                                                                                                                                                                                                                                                                                                                                                                                        marginBottom: '10px',
                                                                                                                                                                                                                                                                                                                                                                                                                                            boxShadow: '0 2px 4px rgba(0, 0, 0, 0.1)',
                                                                                                                                                                                                                                                                                                                                                                                                                                                textAlign: 'center',
                                                                                                                                                                                                                                                                                                                                                                                                                                                  },
                                                                                                                                                                                                                                                                                                                                                                                                                                                  };

                                                                                                                                                                                                                                                                                                                                                                                                                                                  export default App;